Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\JB-env\lib\site-packages\jupyter_cache\executors\utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "C:\ProgramData\Anaconda3\envs\JB-env\lib\site-packages\nbclient\client.py", line 1085, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\ProgramData\Anaconda3\envs\JB-env\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\ProgramData\Anaconda3\envs\JB-env\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\ProgramData\Anaconda3\envs\JB-env\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "C:\ProgramData\Anaconda3\envs\JB-env\lib\site-packages\nbclient\client.py", line 552, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "C:\ProgramData\Anaconda3\envs\JB-env\lib\site-packages\nbclient\client.py", line 846, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "C:\ProgramData\Anaconda3\envs\JB-env\lib\site-packages\nbclient\client.py", line 748, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
%matplotlib notebook
from skimage import io
import numpy as np
from matplotlib import pyplot as plt
from matplotlib import cm
from scipy import ndimage
import os


------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[1;32mC:\Temp\ipykernel_14108\3789179860.py[0m in [0;36m<module>[1;34m[0m
[0;32m      1[0m [0mget_ipython[0m[1;33m([0m[1;33m)[0m[1;33m.[0m[0mrun_line_magic[0m[1;33m([0m[1;34m'matplotlib'[0m[1;33m,[0m [1;34m'notebook'[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[1;32m----> 2[1;33m [1;32mfrom[0m [0mskimage[0m [1;32mimport[0m [0mio[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      3[0m [1;32mimport[0m [0mnumpy[0m [1;32mas[0m [0mnp[0m[1;33m[0m[1;33m[0m[0m
[0;32m      4[0m [1;32mfrom[0m [0mmatplotlib[0m [1;32mimport[0m [0mpyplot[0m [1;32mas[0m [0mplt[0m[1;33m[0m[1;33m[0m[0m
[0;32m      5[0m [1;32mfrom[0m [0mmatplotlib[0m [1;32mimport[0m [0mcm[0m[1;33m[0m[1;33m[0m[0m

[1;31mModuleNotFoundError[0m: No module named 'skimage'
ModuleNotFoundError: No module named 'skimage'

