Traceback (most recent call last):
  File "/opt/conda/envs/science/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/conda/envs/science/lib/python3.11/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/science/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/science/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/conda/envs/science/lib/python3.11/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/opt/conda/envs/science/lib/python3.11/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/conda/envs/science/lib/python3.11/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
gen_FR = word_generator(r"_DATA/dic/FR_aisi.txt")
gen_FR.plot()
plt.show()
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
Cell [0;32mIn[4], line 1[0m
[0;32m----> 1[0m gen_FR [38;5;241m=[39m [43mword_generator[49m[43m([49m[38;5;124;43mr[39;49m[38;5;124;43m"[39;49m[38;5;124;43m_DATA/dic/FR_aisi.txt[39;49m[38;5;124;43m"[39;49m[43m)[49m
[1;32m      2[0m gen_FR[38;5;241m.[39mplot()
[1;32m      3[0m plt[38;5;241m.[39mshow()

Cell [0;32mIn[3], line 14[0m, in [0;36mword_generator.__init__[0;34m(self, dic_file)[0m
[1;32m     11[0m proba_matrix [38;5;241m=[39m [38;5;124mr[39m[38;5;124m"[39m[38;5;124mmatrix_FR.png[39m[38;5;124m"[39m
[1;32m     12[0m [38;5;28mself[39m[38;5;241m.[39moutfile [38;5;241m=[39m [38;5;124mr[39m[38;5;124m"[39m[38;5;124moutput.txt[39m[38;5;124m"[39m
[0;32m---> 14[0m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mread_dic[49m[43m([49m[43m)[49m

Cell [0;32mIn[3], line 20[0m, in [0;36mword_generator.read_dic[0;34m(self)[0m
[1;32m     17[0m [38;5;28mself[39m[38;5;241m.[39mdico [38;5;241m=[39m []  [38;5;66;03m# to store the words of the dictionnary[39;00m
[1;32m     19[0m [38;5;28mself[39m[38;5;241m.[39mcount [38;5;241m=[39m np[38;5;241m.[39mzeros(([38;5;241m256[39m, [38;5;241m256[39m, [38;5;241m256[39m), dtype[38;5;241m=[39m[38;5;124m"[39m[38;5;124mint32[39m[38;5;124m"[39m)
[0;32m---> 20[0m [38;5;28;01mwith[39;00m [43mcodecs[49m[38;5;241;43m.[39;49m[43mopen[49m[43m([49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mdic_file[49m[43m,[49m[43m [49m[38;5;124;43m"[39;49m[38;5;124;43mr[39;49m[38;5;124;43m"[39;49m[43m,[49m[43m [49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mencoding[49m[43m)[49m [38;5;28;01mas[39;00m lines:
[1;32m     21[0m     [38;5;28;01mfor[39;00m l [38;5;129;01min[39;00m lines:
[1;32m     22[0m         [38;5;66;03m# Trimming of the line :[39;00m
[1;32m     23[0m         [38;5;66;03m# Split on white space, tab, slash backslah or open parenthesis[39;00m
[1;32m     24[0m         [38;5;66;03m# and keep the first string, add EOL character[39;00m
[1;32m     25[0m         l2 [38;5;241m=[39m re[38;5;241m.[39msplit([38;5;124m"[39m[38;5;124m[ /[39m[38;5;130;01m\\[39;00m[38;5;130;01m\t[39;00m[38;5;124m,[39m[38;5;124m\[39m[38;5;124m(][39m[38;5;124m"[39m, l)[[38;5;241m0[39m] [38;5;241m+[39m [38;5;124m"[39m[38;5;130;01m\n[39;00m[38;5;124m"[39m

File [0;32m<frozen codecs>:918[0m, in [0;36mopen[0;34m(filename, mode, encoding, errors, buffering)[0m

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: '_DATA/dic/FR_aisi.txt'

